### PR TITLE
Support Appveyor and its dependent changes

### PR DESCRIPTION
**Pull request by cosmo0920**
## Implement Feature

* support to building and testing in AppVeyor CI which works on Windows Server workers.

## Unresolved questions

* <s>Tests are failed in Ruby 2.0.0 and 2.1. Should we support running tests in Ruby 2.0.0 and 2.1?</s>
   - resolved in https://github.com/cosmo0920/win32-api/pull/20/commits/ffc1ba39bbdc6b22c94f4f70194ad71b3e548140

### CODE REVIEW

**Comment by djberg96** [comment]
You shouldn't have to explicitly add the devkit paths, should you? Or is this for appveyor? Otherwise, the "require 'devkit'" should just work as-is.

Also keep in mind with this project that some people might be compiling with Visual Studio.

**Comment by cosmo0920** [comment]
> You shouldn't have to explicitly add the devkit paths, should you? Or is this for appveyor? Otherwise, the "require 'devkit'" should just work as-is.

I intended this for `AppVeyor`.
But it is needless because `devkitvars.{bat, ps1}` sets compiler toolchain path.

What did work `require "devkit"`?
In my environment, I cannot require `devkit` and find `devkit.rb`.

```powershell
PS> ls C:\Devkit


    ディレクトリ: C:\Devkit


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2013/02/24     21:55                bin
d-----       2013/02/24     21:55                etc
d-----       2010/02/06      9:39                include
d-----       2013/02/24     21:55                lib
d-----       2013/02/24     21:55                mingw
d-----       2010/03/18      7:06                postinstall
d-----       2010/04/17     12:53                sbin
d-----       2013/02/24     21:55                share
-a----       2016/04/27      8:01            600 config.yml
-a----       2013/02/24     23:51            297 devkitvars.bat
-a----       2013/02/24     23:51            361 devkitvars.ps1
-a----       2013/02/24     23:51          10232 dk.rb
-a----       2009/07/12      3:34           2238 m.ico
-a----       2010/09/29      8:48           7167 msys.bat
-a----       2009/07/12      3:34          37758 msys.ico
```

**Comment by djberg96** [comment]
@cosmo0920 Doing "require 'devkit'" should just work if you've already setup your Rubies for it. It was my understanding that appveyor already has devkit installed and setup for all of its Rubies, so you' shouldn't have to worry about it.

**Comment by cosmo0920** [comment]
Rebased and I've got AppVeyor CI green!
Can I merge this?

**Comment by djberg96** [comment]
👍

**Pull request merged**
